openapi: 3.0.1
info:
  title: Pipool API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local Docker development
tags:
- name: users
  description: Users related endpoints
paths:
  /users/login:
    post:
      tags:
      - users
      summary: Log in a new user
      requestBody:
        description: User object to create and log in
        content:
          application/json:
            schema:
              required:
              - email
              - password
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        200:
          description: User log in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
      x-codegen-request-body-name: body
  /users/sign-up:
    post:
      tags:
      - users
      summary: Create and log in a new user
      requestBody:
        description: User object to create and log in
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: User created and log in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
        422:
          description: Email already created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
      x-codegen-request-body-name: body
components:
  schemas:
    User:
      required:
      - email
      - password
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
    Authentication:
      type: object
      properties:
        token:
          type: string
          description: Bearer token for authenticated endpoints
        user:
          $ref: '#/components/schemas/User'
    ValidationError:
      type: object
      properties:
        message:
          type: string
          description: Error description
          example: The given data was invalid
        errors:
          type: object
          properties:
            $fieldName:
              type: array
              items:
                type: string
                description: Error description
          description: List of fields failing
